# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32be270a2b3b638af19ee30a11d870669fcffb66c23797618df7938a2d935d849252381c30c07fc5799d69bf4ad3e9ed20411e57a4dae6bc0d3e2f90aee780f5

test:
  secret_key_base: 3d4d68bdd387143f89049a6a4eede796c689159c11367516c0f1132b90c24bc1956c72b4aab5f94dfc8e99ce62bfc5a03723b370a91b53b8834abda5b969cb7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
